services:
  uppy:
    image: transloadit/companion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /tmp/uppy-server-data:/mnt/uppy-server-data
    ports:
      - '3020:3020'
    env_file:
      - .env
